name: Run Tests & Build
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: test

  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build A Snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: build

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          path: build/distributions/*
